//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Year2022.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Year2022.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15560
        ///3906
        ///7076
        ///11980
        ///11508
        ///
        ///6558
        ///2256
        ///7294
        ///6566
        ///2686
        ///2566
        ///1724
        ///4811
        ///5427
        ///4278
        ///3756
        ///
        ///3761
        ///5599
        ///13187
        ///12558
        ///7425
        ///9269
        ///
        ///59658
        ///
        ///34175
        ///9643
        ///
        ///7664
        ///10224
        ///5541
        ///1378
        ///1784
        ///9347
        ///7692
        ///
        ///3786
        ///4260
        ///4416
        ///6345
        ///6750
        ///6415
        ///5467
        ///4898
        ///2017
        ///4486
        ///1198
        ///1960
        ///
        ///5658
        ///6168
        ///8088
        ///7749
        ///5890
        ///1980
        ///6014
        ///1136
        ///3138
        ///6706
        ///7041
        ///
        ///9197
        ///6997
        ///12644
        ///12609
        ///7630
        ///12928
        ///
        ///5278
        ///1423
        ///4822
        ///5148
        ///6387
        ///1280
        ///6431
        ///3847
        ///5886
        ///2714
        ///3725
        ///6331
        ///
        ///7537
        ///6965
        ///10079
        ///8904
        ///8639
        ///10679
        ///8964        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day01 {
            get {
                return ResourceManager.GetString("Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Z
        ///A Z
        ///A Z
        ///B Z
        ///C X
        ///A Z
        ///A Z
        ///C Y
        ///A Z
        ///A Y
        ///B Y
        ///A Z
        ///C X
        ///A Z
        ///A Z
        ///A Z
        ///A Z
        ///A Y
        ///A Z
        ///A Z
        ///C Y
        ///C X
        ///C X
        ///C X
        ///A Z
        ///A Z
        ///B Y
        ///A Z
        ///A Z
        ///C Z
        ///B Z
        ///A Y
        ///A Z
        ///B Y
        ///A Z
        ///B Y
        ///A X
        ///B Z
        ///A Z
        ///A Z
        ///A Z
        ///C X
        ///C X
        ///A X
        ///A Z
        ///A Z
        ///C X
        ///A Z
        ///B Y
        ///A Z
        ///B Z
        ///A Z
        ///A Z
        ///B Z
        ///B Z
        ///C Y
        ///B Z
        ///A X
        ///B Z
        ///A Z
        ///B Y
        ///A Z
        ///B Z
        ///C X
        ///A Z
        ///B Y
        ///B Z
        ///A Z
        ///B Y
        ///C X
        ///B Y
        ///A Z
        ///A Z
        ///A Z
        ///B Y
        ///A Z
        ///A Z
        ///B Y
        ///B Z
        ///C Z
        ///A X
        ///A Z
        ///A Z
        ///C Z
        ///C X
        ///A Z
        ///C X
        ///A Z
        ///A X
        ///A Z
        ///A Z
        ///A Z
        ///B X
        ///B Y
        ///A Z
        ///A Z
        ///A Z
        ///C Y
        ///B Y
        ///C X
        ///C X
        ///A Z
        ///A  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCMRQjLLWGTjnlnZwwnZJRZH
        ///qnvfhpSbvSppNddNdSqbbmmdPrwttJVrVPDVrJtHtwPZhrPJ
        ///BFpFzSSqSFFSvQsnWgCMjTLzng
        ///DbWVcVRRdlLffvtqjTWNgQ
        ///mJJMpsmrMrJSHJpsHrFHvBvgHvqfNvzffgTvfj
        ///mMhPjmjmFPJhMSGGcDRlwRdcLGPc
        ///qFcbmWFJqqWpRJcQWpqsQQQwSPCPrHRHCPdNZtSrSHwrNZ
        ///jGMjGLhhhgTvghgtGVjnNCrPVwZSZffSNSwHZZdH
        ///DvzDlvvhnjlMlglglGGhDLpqqcJWWtsmszpWbBBBmQmb
        ///SPLPHQbJSbPsvTLmfDvVDctvWhcDlD
        ///jdRRzzGgJqwrpMRMgdjlcVcWqfWWlfDlmmlWhB
        ///rwgRGdpGprNNLQLsbZJPsn
        ///GZhTVLztHrSzrRBz
        ///MJWjMvsfSCLSnrJn
        ///MjglcgWMdccvZGFtTDchLLLh
        ///rgDHBgBjRgRTgwzwthBn [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day03 {
            get {
                return ResourceManager.GetString("Day03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1-93,2-11
        ///26-94,26-94
        ///72-92,48-88
        ///36-37,37-52
        ///2-98,1-98
        ///1-83,1-84
        ///74-79,76-76
        ///66-85,66-86
        ///6-73,6-73
        ///31-57,30-58
        ///1-98,1-98
        ///28-47,55-97
        ///29-71,70-72
        ///40-53,40-53
        ///14-71,39-71
        ///19-98,18-94
        ///94-96,81-95
        ///79-98,79-97
        ///52-66,60-61
        ///2-3,8-89
        ///53-59,59-83
        ///79-81,3-80
        ///14-84,84-92
        ///90-90,7-89
        ///10-76,11-76
        ///9-31,10-12
        ///8-8,8-72
        ///2-97,1-96
        ///3-33,2-94
        ///3-5,4-99
        ///46-94,8-94
        ///97-98,14-92
        ///60-98,81-99
        ///11-98,11-97
        ///27-82,26-81
        ///21-61,12-18
        ///26-55,26-56
        ///89-96,97-97
        ///29-30,29-31
        ///66-90,40-87
        ///7-49,8-88
        ///37-61,39 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day04 {
            get {
                return ResourceManager.GetString("Day04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     [L]     [H] [W]
        ///                [J] [Z] [J] [Q] [Q]
        ///[S]             [M] [C] [T] [F] [B]
        ///[P]     [H]     [B] [D] [G] [B] [P]
        ///[W]     [L] [D] [D] [J] [W] [T] [C]
        ///[N] [T] [R] [T] [T] [T] [M] [M] [G]
        ///[J] [S] [Q] [S] [Z] [W] [P] [G] [D]
        ///[Z] [G] [V] [V] [Q] [M] [L] [N] [R]
        /// 1   2   3   4   5   6   7   8   9 
        ///
        ///move 1 from 3 to 5
        ///move 2 from 2 to 8
        ///move 4 from 1 to 3
        ///move 2 from 1 to 4
        ///move 1 from 7 to 1
        ///move 2 from 9 to 7
        ///move 4 from 5 to 9
        ///move 7 from 8 to 9
        ///move 2 from 5 to  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day05 {
            get {
                return ResourceManager.GetString("Day05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mzrzqrzqrrmcmgmrggvjvcczbczccdwdcwcpwwclwwbttdntnsnllpggqhgqgzqggvjjjfqfhhbbvzvmzvvfccnznwntnptpgpcplpwwvgvzvvcgvvbcvcqqhnqqbsbdsbbbgtgvtgvtgvvrfvvjbjcbcchnhrhvvrmmwzwzmwmggjwwwwzrrmbmbmbrrdjrjfrrrmrffzgghtggwddtllhchdhsshjjwfwsfssnbbnjncczsczzvpvssljsjgsjgjcgjggspsfsfhfppsqqzlzjllblsldsldlndnhnffflwfwmwssvzzvqzzblzbbmrrfnrrqnnhfnnhphbhrrlvrlvrvcrrltrtmrrcscchdhqhfffrddzsszwwrbrfftddbwwtdtnndrrghgcgfgrglllcdcsswvwsvszsddjwdwwcvwvmvhhlqlddbhbrrnddpqpttrtctmcmjjtvjjfvvlcldltdtdqdllnrncrnrznzfnfsfnndqqbhhlnhhh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day06 {
            get {
                return ResourceManager.GetString("Day06", resourceCulture);
            }
        }
    }
}
